### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by DmitriyHoriainov** [UMSF-K13-2-Horiainov/MainProject#1]
Создал репозиторий, после подключил студию к гитхабу, потом локальный репозиторий синхронизировал с репозиторием на гитхаб, сделал несколько изменений и закоммитил их.
С основным функционалом гитхаба разобрался, по моему мнению, очень полезный сервис

![4](https://cloud.githubusercontent.com/assets/19636850/15635528/29927708-25e9-11e6-86a4-33fe8904bf64.png)
![5](https://cloud.githubusercontent.com/assets/19636850/15635530/29d39378-25e9-11e6-9816-d69d662aae61.png)

**Comment by Smoktii** [comment]
Ок
